import { prisma } from "@jordan/db";
import { randomUUID } from "node:crypto";

/** Postgres caps a single statement at 65535 bind parameters. */
const PG_MAX_PARAMS = 65535;

export interface BulkColumn {
  name: string;
  /** Explicit cast for types Postgres will not infer from a text parameter. */
  cast?: "jsonb" | "timestamp" | "numeric" | "int" | "boolean" | "text";
}

export interface BulkUpsertOptions {
  table: string;
  columns: BulkColumn[];
  rows: unknown[][];
  /** Columns of the unique index that defines a conflict. */
  conflictColumns: string[];
  /** Columns overwritten when the row already exists. Empty ⇒ DO NOTHING. */
  updateColumns: string[];
  chunkSize?: number;
}

const quote = (id: string): string => `"${id.replace(/"/g, '""')}"`;

/**
 * Chunked `INSERT ... ON CONFLICT DO UPDATE`.
 *
 * Replaces the previous per-record `prisma.upsert()` loop, which cost one round
 * trip per row — at ~125k patients and ~800k reserves that alone dominated the
 * sync. One statement per chunk keeps the whole entity to a few hundred round
 * trips.
 */
export async function bulkUpsert(opts: BulkUpsertOptions): Promise<number> {
  const { table, columns, rows, conflictColumns, updateColumns } = opts;
  if (rows.length === 0) return 0;

  // Never exceed the bind-parameter ceiling regardless of the requested chunk.
  const maxRowsByParams = Math.max(1, Math.floor(PG_MAX_PARAMS / columns.length));
  const chunkSize = Math.max(1, Math.min(opts.chunkSize ?? 500, maxRowsByParams));

  const colList = columns.map((c) => quote(c.name)).join(", ");
  const conflictList = conflictColumns.map(quote).join(", ");
  const setList = updateColumns
    .map((c) => `${quote(c)} = EXCLUDED.${quote(c)}`)
    .join(", ");

  let affected = 0;

  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize);
    const params: unknown[] = [];

    const valuesSql = chunk
      .map((row) => {
        const placeholders = row.map((value, colIndex) => {
          params.push(value);
          const cast = columns[colIndex]?.cast;
          return cast ? `$${params.length}::${cast}` : `$${params.length}`;
        });
        return `(${placeholders.join(", ")})`;
      })
      .join(", ");

    const sql = setList
      ? `INSERT INTO ${quote(table)} (${colList}) VALUES ${valuesSql} ` +
        `ON CONFLICT (${conflictList}) DO UPDATE SET ${setList}`
      : `INSERT INTO ${quote(table)} (${colList}) VALUES ${valuesSql} ` +
        `ON CONFLICT (${conflictList}) DO NOTHING`;

    affected += await prisma.$executeRawUnsafe(sql, ...params);
  }

  return affected;
}

/** Plain chunked insert for child rows that are replaced wholesale. */
export async function bulkInsert(
  opts: Omit<BulkUpsertOptions, "conflictColumns" | "updateColumns">,
): Promise<number> {
  const { table, columns, rows } = opts;
  if (rows.length === 0) return 0;

  const maxRowsByParams = Math.max(1, Math.floor(PG_MAX_PARAMS / columns.length));
  const chunkSize = Math.max(1, Math.min(opts.chunkSize ?? 500, maxRowsByParams));
  const colList = columns.map((c) => quote(c.name)).join(", ");

  let affected = 0;
  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize);
    const params: unknown[] = [];
    const valuesSql = chunk
      .map((row) => {
        const placeholders = row.map((value, colIndex) => {
          params.push(value);
          const cast = columns[colIndex]?.cast;
          return cast ? `$${params.length}::${cast}` : `$${params.length}`;
        });
        return `(${placeholders.join(", ")})`;
      })
      .join(", ");

    affected += await prisma.$executeRawUnsafe(
      `INSERT INTO ${quote(table)} (${colList}) VALUES ${valuesSql}`,
      ...params,
    );
  }
  return affected;
}

/**
 * Surrogate key for tables whose `@id @default(cuid())` is generated by the
 * Prisma client rather than the database — a raw INSERT must supply one.
 * On conflict the existing row keeps its id, since `id` is never in the
 * update column list.
 */
export const newId = (): string => randomUUID();

/**
 * externalCode → Patient.id for the whole table.
 *
 * The previous engine issued `patient.findUnique()` per treatment and per
 * reception row; at reception volumes that is one extra query per record. The
 * map is a few MB for ~125k patients and is built once per entity run.
 */
export async function loadPatientIdMap(): Promise<Map<number, string>> {
  const map = new Map<number, string>();
  const pageSize = 50_000;
  let cursor: string | undefined;

  for (;;) {
    const batch = await prisma.patient.findMany({
      select: { id: true, externalCode: true },
      orderBy: { id: "asc" },
      take: pageSize,
      ...(cursor ? { skip: 1, cursor: { id: cursor } } : {}),
    });
    if (batch.length === 0) break;
    for (const p of batch) map.set(p.externalCode, p.id);
    if (batch.length < pageSize) break;
    cursor = batch[batch.length - 1]!.id;
  }

  return map;
}
